export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const INIT_INGREDIENTS = "INIT_INGREDIENTS";
export const FETCH_INGREDIENTS_FAIL = "FETCH_INGREDIENTS_FAIL";

export const PURCHASE_BURGER = "PURCHASE_BURGER";
export const START_PURCHASE_BURGER = "START_PURCHASE_BURGER";
export const PURCHASE_INIT = "PURCHASE_INIT";
export const PURCHASE_BURGER_FAIL = "PURCHASE_BURGER_FAIL";

export const FETCH_ORDERS = "FETCH_ORDERS";
export const FETCH_ORDERS_FAIL = "FETCH_ORDERS_FAIL";
export const START_FETCH_ORDERS = "START_FETCH_ORDERS";